/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UniversitiesIdRouteImport } from './routes/universities.$id'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as AdminUniversitiesRouteImport } from './routes/admin.universities'
import { Route as AdminScholarshipsRouteImport } from './routes/admin.scholarships'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIdRoute = UniversitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UniversitiesRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/admin/universities',
  path: '/admin/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScholarshipsRoute = AdminScholarshipsRouteImport.update({
  id: '/admin/scholarships',
  path: '/admin/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/courses/$id': typeof CoursesIdRoute
  '/universities/$id': typeof UniversitiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/courses/$id': typeof CoursesIdRoute
  '/universities/$id': typeof UniversitiesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/assistant': typeof AssistantRoute
  '/career': typeof CareerRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/universities': typeof UniversitiesRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/courses/$id': typeof CoursesIdRoute
  '/universities/$id': typeof UniversitiesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/assistant'
    | '/career'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/scholarships'
    | '/settings'
    | '/universities'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/scholarships'
    | '/admin/universities'
    | '/courses/$id'
    | '/universities/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/assistant'
    | '/career'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/scholarships'
    | '/settings'
    | '/universities'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/scholarships'
    | '/admin/universities'
    | '/courses/$id'
    | '/universities/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/assistant'
    | '/career'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/recommendations'
    | '/register'
    | '/scholarships'
    | '/settings'
    | '/universities'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/scholarships'
    | '/admin/universities'
    | '/courses/$id'
    | '/universities/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AssistantRoute: typeof AssistantRoute
  CareerRoute: typeof CareerRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SettingsRoute: typeof SettingsRoute
  UniversitiesRoute: typeof UniversitiesRouteWithChildren
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminScholarshipsRoute: typeof AdminScholarshipsRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  CoursesIdRoute: typeof CoursesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$id': {
      id: '/universities/$id'
      path: '/$id'
      fullPath: '/universities/$id'
      preLoaderRoute: typeof UniversitiesIdRouteImport
      parentRoute: typeof UniversitiesRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/universities': {
      id: '/admin/universities'
      path: '/admin/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scholarships': {
      id: '/admin/scholarships'
      path: '/admin/scholarships'
      fullPath: '/admin/scholarships'
      preLoaderRoute: typeof AdminScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UniversitiesRouteChildren {
  UniversitiesIdRoute: typeof UniversitiesIdRoute
}

const UniversitiesRouteChildren: UniversitiesRouteChildren = {
  UniversitiesIdRoute: UniversitiesIdRoute,
}

const UniversitiesRouteWithChildren = UniversitiesRoute._addFileChildren(
  UniversitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AssistantRoute: AssistantRoute,
  CareerRoute: CareerRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SettingsRoute: SettingsRoute,
  UniversitiesRoute: UniversitiesRouteWithChildren,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminScholarshipsRoute: AdminScholarshipsRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  CoursesIdRoute: CoursesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
